### ISSUE TITLE
Training and Inference

### ISSUE THREAD

**Issue by skuley** [vvirgooo2/MPM#1]
Great Work!

I have some questions just to be clear..

1. During fine-tuning stage (stage II) Do I have to use 2D AND 3D pose? Can I just use 2D pose?
2. Does out_channel in opt.py file describe the output channel of each stage 1 model?
3. In Inference, Can I use 1 frame instead of 81 or 243?

ps. It would be lovely if you share Inference code and checkpoint too!

Thank you very much!

**Comment by vvirgooo2** [comment]
1、Stage II is supervised learning, only using 2D pose is not feasible
2、Output channel in opt.py  is 2 or 3 indicating the dimension of the output joints.
3、You can only use 1 frame but is not in line with the original intention of this job and you may get poor results.
inference code is already in this repo, and the checkpoint for human3.6M is already released.

**Comment by skuley** [comment]
I didn't find any inference code.
Do you mean by test mode in trainer.py file?

Also can you give me access to your google drive?
I have requested a week ago but didn't get any email.

Thanks!

**Comment by vvirgooo2** [comment]
https://github.com/vvirgooo2/MPM#evaluating-our-models

**Comment by vvirgooo2** [comment]
Yes, the inference code is implemented by test mode in the trainer.py file
